name: Auto Commit Everyday ✨

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make empty commit
        run: |
          git config user.name "GitHub Bot 🤖"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Daily Commit 💥"
          git push
